### ISSUE TITLE
Mali gpu issue

### ISSUE THREAD

**Issue by anwardad** [alexvorxx/VirGL-Overlay-Rebuild#1]
When I play games on my Samsung j7  duo using your obb file (and also any cach of exagear on the internet)  the game is so dark  I can't see any thing only well light  portion of games are visible on Adrino  gpu it's fine. If it's Virgl problem I don't know if it's not is there a solution

**Comment by alexvorxx** [comment]
Other users advise to use "Wine 3.0.5 Mali Fix" or Hugo caches. Try to install "wined3d fix mali" in start menu.
Sometimes changing the registry helps (Software - Wine - Direct3D - OffscreenRenderingMode - "backbuffer").

Hugo caches:
https://drive.google.com/file/d/1obk6nSPkHaHrsLDvv4I33gAfQXuYqmts/view
https://drive.google.com/file/d/1MBCCO59blGY5inCJTsVDIYog0ekAyTsZ/view

Wine 3.0.5 Mali Fix:
https://dl.uploadgram.me/628de03ee6914g

**Comment by XHYN-PH** [comment]
As always it can be the game it self or the renderer you used try CSMT or deleting other D3D Regs... Or maybe the phone it self has issues on OpenGL extensions And VirGL is intended for OpenGL only games don't use it for heavy games VirGL is Virtual OpenGL so try OpenGL games like SteamWorld or Old Games from 20's or 90's... 

i recommend cache's from 4pda or Hugo. Join to discord for more infos

**Comment by XHYN-PH** [comment]
Translated:
Как всегда, это может быть сама игра или используемый вами рендерер, попробуйте CSMT или удалите другие регистры D3D ... Или, может быть, у самого телефона есть проблемы с расширениями OpenGL. VirGL предназначен для OpenGL, только игры не используют его для тяжелых игр. VirGL это виртуальный OpenGL, поэтому попробуйте игры OpenGL, такие как SteamWorld или старые игры 20-х или 90-х годов ... я рекомендую кэш от 4pda или Hugo. Присоединяйтесь к раздору для получения дополнительной информации

**Comment by anwardad** [comment]
Thanks for the support  I checked on two different devices one with  Mali g71 and other with Mali g57 mc2 gpu same issue  the games run with good speed  ( eg. silent hill home coming,dead space 1,hitman blood money ) but I can't see where I'm going most of the time I have modefid the shortcut to force Mesa GL 4.5 so I could have tesselation and it works in direct X 11 games and supports up to direct X 11.1 game 
Some workround I found is to set game resolution higher than container resolution and setting color to 16 bit also work on some games (mafia 2) but not on most I will try the links thanks
