### ISSUE TITLE
How to use it with box86 in chroot

### ISSUE THREAD

**Issue by Bluecommand** [alexvorxx/VirGL-Overlay-Rebuild#2]
Where is '.virgl_test' file. Thanks.

**Comment by alexvorxx** [comment]
- Download and unpack archive with modified Mesa 21.1.3 for VirGL:
   https://drive.google.com/file/d/1ObnYUsFi1uABizJrZIuO5c7BCjJtgCm7/view?usp=sharing

   `apt-get build-dep mesa`

   `cd mesa-21.1.3`

   `meson . build -Dgallium-va=disabled -Ddri-drivers= -Dgallium-drivers=virgl -Ddri3=disabled -Dvulkan-drivers= -Dglx=gallium-xlib -Dplatforms=x11 -Dtools= -Dllvm=false -Dbuildtype=release`

   `ninja -C build install`

- Run VirGL Overlay apk.

- Draw in X11, not in overlay (optional):

   `export VTEST_WIN=1 `

**Comment by Bluecommand** [comment]
> * Download and unpack archive with modified Mesa 21.1.3 for VirGL:
>   https://drive.google.com/file/d/1ObnYUsFi1uABizJrZIuO5c7BCjJtgCm7/view?usp=sharing
>   `apt-get build-dep mesa`
>   `cd mesa-21.1.3`
>   `meson . build -Dgallium-va=disabled -Ddri-drivers= -Dgallium-drivers=virgl -Ddri3=disabled -Dvulkan-drivers= -Dglx=gallium-xlib -Dplatforms=x11 -Dtools= -Dllvm=false -Dbuildtype=release`
>   `ninja -C build install`
> * Run VirGL Overlay apk.
> * Draw in X11, not in overlay (optional):
>   `export VTEST_WIN=1 `

thanks it works well

**Comment by IntinteDAO** [comment]
@alexvorxx 
Is it possible to run VirGL Overlay with Termux? And if yes, do you have newest version of Mesa?

I have also one question about:
https://github.com/alexvorxx/Zink-Mesa-Xlib

It can run Zink on Termux or not?

**Comment by alexvorxx** [comment]
> 

It's possible.
There is one of the latest versions of Mesa 22.3.1.
How to build and install:

Download and unpack archive with modified Mesa 22.3.1 for VirGL:
https://drive.google.com/file/d/1RA2XsEOotbrTwlcTQeSr-eBAsjljRa38/view?usp=sharing

`apt-get build-dep mesa`

`cd mesa-22.3.1`

`meson . build -Dgallium-va=disabled -Ddri-drivers= -Dgallium-drivers=virgl -Ddri3=disabled -Dvulkan-drivers= -Dglx=xlib -Dplatforms=x11 -Dtools= -Dllvm=false -Dbuildtype=release`

`ninja -C build install`


About Turnip and Zink. You can compile and install this in Termux, see README.

**Comment by ThieuMinh26** [comment]
> @alexvorxx Is it possible to run VirGL Overlay with Termux? And if yes, do you have newest version of Mesa?
> 
> I have also one question about: https://github.com/alexvorxx/Zink-Mesa-Xlib
> 
> It can run Zink on Termux or not?

https://youtu.be/M4ozL45gl1E
